"""adiciona coluna ativo na tabela alunos

Revision ID: 019968499978
Revises: 1e5d57513480
Create Date: 2026-05-29 10:25:15.956262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019968499978'
down_revision = '1e5d57513480'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'alunos' in tables:
        cols = [c['name'] for c in inspector.get_columns('alunos')]
        with op.batch_alter_table('alunos', schema=None) as batch_op:
            if 'ativo' not in cols:
                batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
                batch_op.create_index(batch_op.f('ix_alunos_ativo'), ['ativo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_ativo'))
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
