"""completando todos os campos da ficha de alunos

Revision ID: 15d6c42e6a4b
Revises: 89313c0be465
Create Date: 2026-05-27 13:03:27.351273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d6c42e6a4b'
down_revision = '89313c0be465'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('raca_cor', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('naturalidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nome_mae', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nome_pai', sa.String(length=100), nullable=True))
        
        # 🔍 ALTERE ESSAS LINHAS ABAIXO DE False PARA True:
        batch_op.add_column(sa.Column('recebe_bpc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('codigo_inep', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('modalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('etapa_ensino', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recurso_ledor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurso_transcritor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurso_libras', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurso_ampliado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('local_aee', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('necessita_apoio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('necessita_transporte_adaptado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cadeirante', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('necessita_acompanhante', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('possui_monitor_rota', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('possui_monitor_rota')
        batch_op.drop_column('necessita_acompanhante')
        batch_op.drop_column('cadeirante')
        batch_op.drop_column('necessita_transporte_adaptado')
        batch_op.drop_column('necessita_apoio')
        batch_op.drop_column('local_aee')
        batch_op.drop_column('recurso_ampliado')
        batch_op.drop_column('recurso_libras')
        batch_op.drop_column('recurso_transcritor')
        batch_op.drop_column('recurso_ledor')
        batch_op.drop_column('etapa_ensino')
        batch_op.drop_column('modalidade')
        batch_op.drop_column('codigo_inep')
        batch_op.drop_column('recebe_bpc')
        batch_op.drop_column('nome_pai')
        batch_op.drop_column('nome_mae')
        batch_op.drop_column('naturalidade')
        batch_op.drop_column('raca_cor')
        batch_op.drop_column('sexo')
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
