"""atualizar checklist paee

Revision ID: 1e5d57513480
Revises: d4dc43d555a9
Create Date: 2026-05-28 19:08:37.199395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5d57513480'
down_revision = 'd4dc43d555a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_regente', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('periodo_vigencia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('necessidades_checklist_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('objetivo_geral', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('objetivos_especificos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('organizacao_atendimento_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recursos_pedagogicos_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tecnologia_assistiva_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('acompanhamento_bimestral_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('articulacao_saude_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metodologias_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nome_regente', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_aee', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_coordenacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_responsavel', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_semec', sa.String(length=255), nullable=True))
        batch_op.drop_column('articulacao_professores_regentes')
        batch_op.drop_column('recursos_pedagogicos_acessiveis')
        batch_op.drop_column('interfaces_institucionais_saude')
        batch_op.drop_column('objetivos_aee')
        batch_op.drop_column('tecnologia_assistiva_especifica')
        batch_op.drop_column('criterios_avaliacao_progresso')
        batch_op.drop_column('organizacao_espaco_tempo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizacao_espaco_tempo', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criterios_avaliacao_progresso', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tecnologia_assistiva_especifica', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('objetivos_aee', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interfaces_institucionais_saude', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recursos_pedagogicos_acessiveis', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('articulacao_professores_regentes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('nome_semec')
        batch_op.drop_column('nome_responsavel')
        batch_op.drop_column('nome_coordenacao')
        batch_op.drop_column('nome_aee')
        batch_op.drop_column('nome_regente')
        batch_op.drop_column('metodologias_json')
        batch_op.drop_column('articulacao_saude_json')
        batch_op.drop_column('acompanhamento_bimestral_json')
        batch_op.drop_column('tecnologia_assistiva_json')
        batch_op.drop_column('recursos_pedagogicos_json')
        batch_op.drop_column('organizacao_atendimento_json')
        batch_op.drop_column('objetivos_especificos')
        batch_op.drop_column('objetivo_geral')
        batch_op.drop_column('necessidades_checklist_json')
        batch_op.drop_column('periodo_vigencia')
        batch_op.drop_column('professor_regente')

    # ### end Alembic commands ###
