"""criando tabela de escolas

Revision ID: 723400b2dcad
Revises: 03f3f8384a61
Create Date: 2026-05-27 11:58:40.895413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723400b2dcad'
down_revision = '03f3f8384a61'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'escolas' not in tables:
        op.create_table('escolas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('municipio_id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=150), nullable=False),
        sa.Column('codigo_inep', sa.String(length=20), nullable=False),
        sa.Column('cnpj', sa.String(length=18), nullable=True),
        sa.Column('diretora_nome', sa.String(length=100), nullable=False),
        sa.Column('diretora_cpf', sa.String(length=14), nullable=True),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('email_institucional', sa.String(length=100), nullable=True),
        sa.Column('zona', sa.String(length=10), nullable=False),
        sa.Column('endereco_rua', sa.String(length=150), nullable=False),
        sa.Column('numero', sa.String(length=20), nullable=True),
        sa.Column('bairro', sa.String(length=80), nullable=False),
        sa.Column('cep', sa.String(length=10), nullable=True),
        sa.Column('possui_sala_recursos', sa.Boolean(), nullable=False),
        sa.Column('possui_rampas', sa.Boolean(), nullable=False),
        sa.Column('possui_banheiro_adaptado', sa.Boolean(), nullable=False),
        sa.Column('possui_portas_largas', sa.Boolean(), nullable=False),
        sa.Column('possui_sinalizacao_tatil', sa.Boolean(), nullable=False),
        sa.Column('modalidades_atendidas', sa.String(length=200), nullable=True),
        sa.Column('total_salas_aula', sa.Integer(), nullable=True),
        sa.Column('criado_em', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('escolas', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_escolas_codigo_inep'), ['codigo_inep'], unique=True)
            batch_op.create_index(batch_op.f('ix_escolas_municipio_id'), ['municipio_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_escolas_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escolas_nome'))
        batch_op.drop_index(batch_op.f('ix_escolas_municipio_id'))
        batch_op.drop_index(batch_op.f('ix_escolas_codigo_inep'))

    op.drop_table('escolas')
    # ### end Alembic commands ###
