"""adicionando coluna cpf em alunos corrigido

Revision ID: 89313c0be465
Revises: c39f0f74e84f
Create Date: 2026-05-27 12:53:08.033961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89313c0be465'
down_revision = 'c39f0f74e84f'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'alunos' in tables:
        cols = [c['name'] for c in inspector.get_columns('alunos')]
        with op.batch_alter_table('alunos', schema=None) as batch_op:
            if 'cpf' not in cols:
                batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
                batch_op.create_index(batch_op.f('ix_alunos_cpf'), ['cpf'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_cpf'))
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
