"""atualizando relacionamento de escola em alunos

Revision ID: c39f0f74e84f
Revises: 723400b2dcad
Create Date: 2026-05-27 12:10:44.364823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39f0f74e84f'
down_revision = '723400b2dcad'
branch_labels = None
depends_on = None


def upgrade():
    # Altere de False para True temporariamente para permitir a criação da coluna
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escola_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alunos_escola_id'), ['escola_id'], unique=False)
        batch_op.create_foreign_key(None, 'escolas', ['escola_id'], ['id'])
        batch_op.drop_column('escola')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escola', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alunos_escola_id'))
        batch_op.drop_column('escola_id')

    # ### end Alembic commands ###
