"""Injecao dos campos AEE corrigida

Revision ID: c473b401e05b
Revises: 019968499978
Create Date: 2026-07-14 17:28:44.323603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c473b401e05b'
down_revision = '019968499978'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'agenda_aee' in tables:
        cols = [c['name'] for c in inspector.get_columns('agenda_aee')]
        with op.batch_alter_table('agenda_aee', schema=None) as batch_op:
            if 'status' not in cols:
                batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
            if 'ativo' not in cols:
                batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
            if 'criado_em' not in cols:
                batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    if 'documentos_aee' in tables:
        cols = [c['name'] for c in inspector.get_columns('documentos_aee')]
        with op.batch_alter_table('documentos_aee', schema=None) as batch_op:
            if 'profissional_id' not in cols:
                batch_op.add_column(sa.Column('profissional_id', sa.Integer(), nullable=True))
            if 'conteudo' not in cols:
                batch_op.add_column(sa.Column('conteudo', sa.Text(), nullable=True))
            if 'chave_autenticidade' not in cols:
                batch_op.add_column(sa.Column('chave_autenticidade', sa.String(length=64), nullable=True))
            if 'status' not in cols:
                batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
            if 'ativo' not in cols:
                batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))

    if 'evolucoes_aee' in tables:
        cols = [c['name'] for c in inspector.get_columns('evolucoes_aee')]
        with op.batch_alter_table('evolucoes_aee', schema=None) as batch_op:
            if 'comportamento_subjetivo' not in cols:
                batch_op.add_column(sa.Column('comportamento_subjetivo', sa.Text(), nullable=True))
            if 'proximos_passos' not in cols:
                batch_op.add_column(sa.Column('proximos_passos', sa.Text(), nullable=True))
            if 'ativo' not in cols:
                batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
            if 'criado_em' not in cols:
                batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evolucoes_aee', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('ativo')
        batch_op.drop_column('proximos_passos')
        batch_op.drop_column('comportamento_subjetivo')

    with op.batch_alter_table('documentos_aee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('url_arquivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('ativo')
        batch_op.drop_column('status')
        batch_op.drop_column('chave_autenticidade')
        batch_op.drop_column('conteudo')
        batch_op.drop_column('profissional_id')

    with op.batch_alter_table('agenda_aee', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('ativo')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
