"""criar tabela paees

Revision ID: d4dc43d555a9
Revises: 15d6c42e6a4b
Create Date: 2026-05-28 17:46:12.969996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dc43d555a9'
down_revision = '15d6c42e6a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('objetivos_aee', sa.Text(), nullable=True),
    sa.Column('organizacao_espaco_tempo', sa.Text(), nullable=True),
    sa.Column('recursos_pedagogicos_acessiveis', sa.Text(), nullable=True),
    sa.Column('tecnologia_assistiva_especifica', sa.Text(), nullable=True),
    sa.Column('articulacao_professores_regentes', sa.Text(), nullable=True),
    sa.Column('orientacao_familia', sa.Text(), nullable=True),
    sa.Column('interfaces_institucionais_saude', sa.Text(), nullable=True),
    sa.Column('criterios_avaliacao_progresso', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estudos_caso', schema=None) as batch_op:
        batch_op.drop_column('informacoes_escolares')
        batch_op.drop_column('observacao_pedagogica')
        batch_op.drop_column('entrevista_familia')

    with op.batch_alter_table('peis', schema=None) as batch_op:
        batch_op.drop_column('barreiras_atitudinais')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barreiras_atitudinais', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('estudos_caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrevista_familia', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observacao_pedagogica', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('informacoes_escolares', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('paees')
    # ### end Alembic commands ###
