"""Adiciona coluna ativo na tabela profissionais_aee

Revision ID: e2658e98ec63
Revises: c473b401e05b
Create Date: 2026-07-14 18:08:31.483516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2658e98ec63'
down_revision = 'c473b401e05b'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'profissionais_aee' in tables:
        cols = [c['name'] for c in inspector.get_columns('profissionais_aee')]
        with op.batch_alter_table('profissionais_aee', schema=None) as batch_op:
            if 'ativo' not in cols:
                batch_op.add_column(sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais_aee', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
